// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Substitua pelos valores reais do seu projeto Supabase:
const supabaseUrl = 'https://fozwfwtbmsupxwmqwgss.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvendmd3RibXN1cHh3bXF3Z3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTM3OTIsImV4cCI6MjA2Njk4OTc5Mn0.eKD9is4hXM8pO7cz0ZMMUkjs1naFcFuE2pcxuRm6zUA';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);