// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fozwfwtbmsupxwmqwgss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvendmd3RibXN1cHh3bXF3Z3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTM3OTIsImV4cCI6MjA2Njk4OTc5Mn0.eKD9is4hXM8pO7cz0ZMMUkjs1naFcFuE2pcxuRm6zUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});